name: test-workflow
on: push

jobs:
  label:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm audit

  artifact:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Sleep for 5 minutes
        run: sleep 3000s
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: test.txt

  parallel-with-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [1,2,'hello']
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm audit

  dependency-example:
    runs-on: ubuntu-latest
    needs:
        - parallel-with-matrix
        - label
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm audit
