name: test-workflow
on: push

jobs:
  label:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  parallel-with-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [1,2,3]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm audit
